### ISSUE TITLE
Paper addition

### ISSUE THREAD

**Issue by eduardo-r** [shamangary/awesome-local-global-descriptor#12]
Thought it was worth including this related paper I came across from naverlabs.
"From handcrafted to deep local features", Gabriela Csurka, Christopher R. Dance, Martin Humenberger. 2019

https://arxiv.org/pdf/1807.10254v3.pdf

Cheers

**Comment by eduardo-r** [comment]
Similarly, this one seems relevant 
"Comparative Evaluation of Hand-Crafted and Learned Local Features".
J.L. Schönberger, H. Hardmeier, T. Sattler and M. Pollefeys. CVPR 2017.
https://github.com/ahojnnes/local-feature-evaluation

**Comment by shamangary** [comment]
Thank you I will add them :)
