### ISSUE TITLE
Questions about Matching loss for affinity matrix

### ISSUE THREAD

**Issue by ghoshaw** [shamangary/awesome-local-global-descriptor#13]
Hi, I have some questions about the Matching loss for affinity matrix. 
The affinity matrix M in your paper 
![image](https://user-images.githubusercontent.com/23494873/80330675-62026a80-8878-11ea-93cb-62d211853fd7.png), With my understanding，its shape is  (HW)*(HW), because each point in Fa must interact with every point in Fp to find the max corresponding.  So, Fa is (HW)*C, and Fp is C*(HW).
The loss Sa,p is calc by finding all the max corresponding for the two featrure map. But 
![image](https://user-images.githubusercontent.com/23494873/80330888-113f4180-8879-11ea-9ff7-46788a120e9c.png) confused me,  in D2-net, the soft detection score M(det) seems to be H*W*C, so which part is wrong?

**Comment by shamangary** [comment]
Hello @ghoshaw, thank you for your interest for our work. The detection score from D2-Net can be reduce to channel=1 by selecting the maximum value or taking the norm of the descriptor feature map, after that we also computer the affinity of the detection score therefore it's also (HW x HW).
