### ISSUE TITLE
Thank you for this repo, I have something you might want to add

### ISSUE THREAD

**Issue by AlphonsG** [shamangary/awesome-local-global-descriptor#4]
Hello, because of this repo I found something I was just about to give up on searching for. Thank you so much, it will help my project. Do you think you can add these to the page as well:

https://github.com/tensorflow/models/tree/master/research/delf  (there is also a paper on the repo)

https://github.com/yzhq97/cnn-registration (there is also a paper on the repo)

**Comment by shamangary** [comment]
Glad I can help 😸. Sure I will add them.
