### ISSUE TITLE
Will there be code provided for reproducing UR2KID?

### ISSUE THREAD

**Issue by HugoFeng** [shamangary/awesome-local-global-descriptor#5]
Hi,
Nice summary and paper. Are you planning to provide source code for training and testing UR2Kid? Thanks.

**Comment by shamangary** [comment]
Hello. Our team members are currently in a new phase right now. It is possible that we will release the testing version. However, the training part may not be released in the future

**Comment by HugoFeng** [comment]
Ok, thanks for the reply.
