### ISSUE TITLE
New_Paper_CVPR_2017 Paper "Learning Discriminative and Transformation Covariant Local Feature Detectors"

### ISSUE THREAD

**Issue by usamasadiq706** [shamangary/awesome-local-global-descriptor#8]
Hi,
First of all awesome work. Your this repository helped me a lot during my literature review and my research work.
Second, just a minor addition. Here is a great paper "Learning Discriminative and Transformation Covariant Local Feature Detectors" of CVPR2017.
Please add it in your repository.
Thanks.

**Comment by shamangary** [comment]
My pleasure ;)
